apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdockerdeploy
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: springbootdockerimage
          image: dockeracr98.azurecr.io/springbootdocker:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: springbootdocker-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: web